name: Expo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Expo project
        run: npm run build

      - name: Deploy to Expo
        run: npx expo upload:android --key <your-expo-key>
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
